const APP_INSIGHTS = Object.freeze({
  INSTANCE_NAME: process.env.APP_INSIGHTS_INSTANCE_NAME,
  INSTRUMENTATION_KEY: process.env.APP_INSIGHTS_INSTRUMENTATION_KEY,
  NAME: 'CRUD-API',
  RESOURCE_GROUP: process.env.APP_INSIGHTS_RESOURCE_GROUP,
  SUBSCRIPTION_ID: process.env.APP_INSIGHTS_SUBSCRIPTION_ID,
  TENANT_ID: process.env.APP_INSIGHTS_TENANT_ID,
})

const APP_NAME = 'CRUD'

const ENVIRONMENT = 'DEV'

module.exports = { APP_INSIGHTS, APP_NAME, ENVIRONMENT }
