const APP_INSIGHTS = Object.freeze({
  INSTANCE_NAME: process.env.APP_INSIGHTS_INSTANCE_NAME,
  INSTRUMENTATION_KEY: process.env.APP_INSIGHTS_INSTRUMENTATION_KEY,
  LOG_NAME: 'API - TODOS',
  QUERIES: {
    REQUEST_BY_SESSION_ID_REQUEST_ID: 'REQUEST_BY_SESSION_ID_REQUEST_ID',
  },
  RESOURCE_GROUP: process.env.APP_INSIGHTS_RESOURCE_GROUP,
  SUBSCRIPTION_ID: process.env.APP_INSIGHTS_SUBSCRIPTION_ID,
  TENANT_ID: process.env.APP_INSIGHTS_TENANT_ID,
})

module.exports = { APP_INSIGHTS }
